const github = "https://github.com/JerzySukiennik";
const projects = [
  {id:"gzowo-ai",name:"Gzowo AI",accent:"#9ee9ff",cover:"assets/covers/gzowo-ai.png",type:"Private build",link:github,linkLabel:"View on GitHub",summary:"A voice-first personal AI cockpit: wake it with a phrase, speak naturally, and let a living interface handle the rest.",story:"Gzowo AI is designed as a personal command centre rather than a chat box. A custom voice interface, animated avatar and tool-driven widgets make it feel present without turning the screen into a dashboard.",stack:["Gemini Live","Canvas","Firebase","Vosk"],images:["assets/source/gzowo-ai-talking.png","assets/source/gzowo-ai-idle.png"]},
  {id:"gsp",name:"GSP",accent:"#ff9e59",cover:"assets/covers/gsp.png",type:"Live project",link:"https://gspaerospace.pl/",linkLabel:"Go to project",summary:"A personal aerospace brand for model rockets, 3D-printed flight hardware and every launch along the way.",story:"GSP turns real flight work into a living archive: flight hardware, launch footage and the experiments behind each new vehicle. It is equal parts maker log, brand and engineering playground.",stack:["HTML","CSS","JavaScript","Firebase"],images:["projectimages/GSP/1.jpg","projectimages/GSP/2.jpg","projectimages/GSP/3.jpg"]},
  {id:"gzowo-bowling",name:"Gzowo Bowling",accent:"#ff5ead",cover:"assets/covers/gzowo-bowling.png",type:"Live game",link:"https://jerzysukiennik.github.io/gzowo-bowling/",linkLabel:"Go to project",summary:"A Jackbox-style party bowling game: phones are the controllers, the big screen is the alley.",story:"Gather friends around one screen, scan in with a phone and throw a real physics-powered ball. Spin, weight, themed lanes, replays and a full bowling score system turn a familiar game into a room-sized event.",stack:["Three.js","Rapier","Firebase RTDB"],images:["projectimages/Gzowo Bowling/1.jpg"]},
  {id:"modular",name:"Modular",accent:"#9ee875",cover:"assets/covers/modular.png",type:"Live game",link:"https://play-modular.netlify.app/",linkLabel:"Go to project",summary:"A bite-size multiplayer civilisation game built from a world of modular strategy tiles.",story:"Modular makes the satisfaction of a long strategy session immediate. Players grow a small living island through tactical tile placement, then compete in the same compact world.",stack:["Three.js","Firebase RTDB","JavaScript"],images:["projectimages/Modular/1.jpg","projectimages/Modular/2.jpg","projectimages/Modular/3.jpg"]},
  {id:"grand-conductors",name:"Grand Conductors",accent:"#ffe066",cover:"assets/covers/grand-conductors.png",type:"Live game",link:"https://jerzysukiennik.github.io/train-conductors/",linkLabel:"Go to project",summary:"A co-op party game where phones run bright little trains across one shared island.",story:"One person is never enough. Players accelerate trains, flip shared switches, honk at sheep and race to deliver passengers before the network turns into a charming disaster.",stack:["Three.js","Firebase RTDB","WebGL"],images:[]},
  {id:"viewfinder",name:"Viewfinder",accent:"#b6a3ff",cover:"assets/covers/viewfinder.png",type:"Live game",link:"https://jerzysukiennik.github.io/viewfinder-capture/",linkLabel:"Go to project",summary:"Photograph part of a world, place the picture, and walk into the geometry you captured.",story:"Viewfinder is a browser puzzle experiment with real geometry operations. Captures cut through the scene, placed photos become walkable objects, and every solution asks you to rethink what a picture can be.",stack:["three.js","CSG","BVH"],images:[]},
  {id:"backrooms",name:"Backrooms Labirynth",accent:"#d1c56a",cover:"assets/covers/backrooms.png",type:"Live game",link:"https://jerzysukiennik.github.io/backrooms-labirynth/",linkLabel:"Go to project",summary:"A 1–4 player escape-room horror game rendered like a lost PS1 memory.",story:"Rooms, keys and unsettling physics puzzles stand between the players and an exit gate. The horror comes from spaces that feel wrong, not monsters: flickering lights, knocks, whispers and things just beyond sight.",stack:["Three.js","Rapier","WebRTC"],images:["projectimages/Backrooms/1.jpg"]},
  {id:"raft",name:"Raft",accent:"#73d6dc",cover:"assets/covers/raft.png",type:"Live game",link:"https://jerzysukiennik.github.io/raft",linkLabel:"Go to project",summary:"Build a raft, hook what the ocean gives you, and survive an endless procedural sea.",story:"Raft is a deterministic survival simulation with a clean separation between its game engine and presentation. Start with a bare platform, gather drifting materials and turn improvisation into a floating home.",stack:["Three.js","Vite","JavaScript"],images:[]},
  {id:"mars-logistics",name:"Mars Logistics",accent:"#ff7652",cover:"assets/covers/mars-logistics.png",type:"Project build",link:"https://github.com/JerzySukiennik/mars-logistics-mp",linkLabel:"View on GitHub",summary:"A multiplayer logistics experiment set on a harsh Martian worksite.",story:"Mars Logistics turns a hostile red world into a shared operations challenge. Vehicles, materials and a growing base give every choice a visible consequence in the landscape.",stack:["Three.js","Rapier","Firebase RTDB"],images:[]},
  {id:"brain-console",name:"Brain Console",accent:"#f1f5ff",cover:"assets/covers/brain-console.png",type:"Local tool",link:github,linkLabel:"View on GitHub",summary:"A read-only visual console for navigating a personal Obsidian second brain.",story:"Brain Console turns a private knowledge vault into a living graph. It maps links, recent changes, project states and notes without ever writing to the underlying archive.",stack:["Node.js","SSE","Obsidian"],images:["assets/source/brain-console-icon.png"]}
];
const $ = (s,p=document)=>p.querySelector(s); const vibe=pattern=>navigator.vibrate?.(pattern);
function escape(s){return s.replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));}
function card(p,i){const target=p.linkLabel==="Go to project"?"Go to project":"View on GitHub";return `<section class="project" id="${p.id}" style="--accent:${p.accent}" data-id="${p.id}"><div class="project-info"><p class="project-index">${String(i+1).padStart(2,"0")} / 10 · ${p.type}</p><h2>${escape(p.name)}</h2><p class="project-summary">${escape(p.summary)}</p><div class="tags">${p.stack.map(x=>`<span>${escape(x)}</span>`).join("")}</div><button class="project-action" data-open="${p.id}">Explore <span>→</span></button></div><div class="project-image"><img src="${p.cover}" alt="Atmospheric cover for ${escape(p.name)}" loading="lazy"><a class="image-link" href="${p.link}" target="_blank" rel="noreferrer"><span>${target} →</span></a></div></section>`}
function build(){const root=$("#projects"),rail=$("#rail");root.innerHTML=projects.map(card).join("");[...projects].forEach(p=>{const b=document.createElement("button");b.setAttribute("aria-label",`Go to ${p.name}`);b.title=p.name;b.onclick=()=>{vibe(10);document.getElementById(p.id).scrollIntoView({behavior:"smooth"})};rail.append(b)});document.addEventListener("click",e=>{const id=e.target.closest("[data-open]")?.dataset.open;if(id)openProject(projects.find(p=>p.id===id))});}
function openProject(p){const d=$("#project-dialog"),slides=[p.cover,...p.images];d.style.setProperty("--accent",p.accent);d.innerHTML=`<article class="detail"><div class="detail-top"><p class="kicker">${p.type}</p><button class="close" aria-label="Close project">Close ×</button></div><h2>${escape(p.name)}</h2><div class="detail-grid"><div class="detail-copy"><p>${escape(p.summary)}</p><h3>Inside the project</h3><p>${escape(p.story)}</p><h3>Built with</h3><p>${escape(p.stack.join(" · "))}</p><div class="detail-links"><a href="${p.link}" target="_blank" rel="noreferrer">${p.linkLabel} ↗</a></div></div><div class="gallery">${slides.map((x,i)=>`<img src="${x}" alt="${escape(p.name)} image ${i+1}" ${i?"loading=\"lazy\"":""}>`).join("")}<div class="gallery-dots">${slides.map((_,i)=>`<button class="${i?"":"active"}" aria-label="Show image ${i+1}"></button>`).join("")}</div></div></div></article>`;d.showModal();history.pushState({project:p.id},"",`#${p.id}`);vibe([12,25,12]);$(".close",d).onclick=()=>closeProject();$(".gallery",d).querySelectorAll(".gallery-dots button").forEach((b,i)=>b.onclick=()=>{vibe(8);$(".gallery",d).querySelectorAll("img").forEach((im,k)=>im.style.opacity=k===i?1:0);$(".gallery",d).querySelectorAll("button").forEach((x,k)=>x.classList.toggle("active",k===i))});}
function closeProject(){const d=$("#project-dialog");if(d.open)d.close();if(history.state?.project)history.back();vibe(10)}
$("#project-dialog").addEventListener("close",()=>{if(history.state?.project)history.replaceState(null,"",location.pathname+location.search)});window.addEventListener("popstate",()=>{const d=$("#project-dialog");if(d.open)d.close()});
function webgl(){const c=$("#space"),gl=c.getContext("webgl",{alpha:false,antialias:false,powerPreference:"high-performance"});if(!gl)return;const vs=`attribute vec2 p;void main(){gl_Position=vec4(p,0.,1.);}`,fs=`precision mediump float;uniform vec2 r;uniform float t;uniform vec3 a;void main(){vec2 uv=(gl_FragCoord.xy-.5*r)/r.y;float n=sin(uv.x*5.+t*.2)+sin(uv.y*7.-t*.17);float wave=sin(length(uv)*12.-t*.7+n)*.5+.5;float glow=.018/(abs(wave-.52)+.025);vec3 col=vec3(.016,.02,.04)+a*glow*.26;col+=a*.09/(length(uv-vec2(sin(t*.09)*.3,cos(t*.12)*.16))+.13);gl_FragColor=vec4(col,1.);}`;function sh(type,src){let s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);return s}let pr=gl.createProgram();gl.attachShader(pr,sh(gl.VERTEX_SHADER,vs));gl.attachShader(pr,sh(gl.FRAGMENT_SHADER,fs));gl.linkProgram(pr);gl.useProgram(pr);let b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,3,-1,-1,3]),gl.STATIC_DRAW);let loc=gl.getAttribLocation(pr,"p");gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,2,gl.FLOAT,false,0,0);let accent=[.4,.8,1],size=()=>{c.width=Math.round(innerWidth*.75);c.height=Math.round(innerHeight*.75);gl.viewport(0,0,c.width,c.height)};size();addEventListener("resize",size);document.querySelectorAll(".panel,.project").forEach(x=>new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){let hex=getComputedStyle(e.target).getPropertyValue("--accent").trim();if(hex?.startsWith("#"))accent=[1,3,5].map(i=>parseInt(hex.slice(i,i+2),16)/255)}}),{threshold:.55}).observe(x));function draw(ms){gl.uniform2f(gl.getUniformLocation(pr,"r"),c.width,c.height);gl.uniform1f(gl.getUniformLocation(pr,"t"),ms*.001);gl.uniform3fv(gl.getUniformLocation(pr,"a"),accent);gl.drawArrays(gl.TRIANGLES,0,3);requestAnimationFrame(draw)}requestAnimationFrame(draw)}
build();webgl();if(location.hash){setTimeout(()=>document.querySelector(location.hash)?.scrollIntoView(),100)}
